#!/usr/bin/env Rscript

# Load required libraries
suppressPackageStartupMessages({
  library(Seurat)
})

# Get command line arguments
args <- commandArgs(trailingOnly = TRUE)

# Help function
show_help <- function() {
  cat("Seurat Object Inspector\n")
  cat("======================\n\n")
  cat("DESCRIPTION:\n")
  cat("  This script reads a Seurat RDS object and provides a comprehensive summary\n")
  cat("  of its structure and contents in a clean, formatted output.\n\n")
  cat("USAGE:\n")
  cat("  Rscript seurat_inspector.R <path_to_seurat_rds>\n")
  cat("  Rscript seurat_inspector.R -h | --help\n\n")
  cat("ARGUMENTS:\n")
  cat("  path_to_seurat_rds    Path to the RDS file containing a Seurat object\n\n")
  cat("OPTIONS:\n")
  cat("  -h, --help           Show this help message and exit\n\n")
  cat("OUTPUT INCLUDES:\n")
  cat("  • Basic object information (cells, features, class)\n")
  cat("  • Assay details (names, dimensions, available data slots)\n")
  cat("  • Dimensionality reductions (PCA, UMAP, tSNE, etc.)\n")
  cat("  • Metadata column summary with data types and ranges\n")
  cat("  • Clustering information (if clusters are present)\n")
  cat("  • Active cell identities and levels\n")
  cat("  • Additional object components (graphs, neighbors, commands)\n\n")
  cat("EXAMPLES:\n")
  cat("  # Inspect a Seurat object\n")
  cat("  Rscript seurat_inspector.R my_seurat_object.rds\n\n")
  cat("  # Show help\n")
  cat("  Rscript seurat_inspector.R -h\n\n")
  cat("REQUIREMENTS:\n")
  cat("  • R with Seurat package installed\n")
  cat("  • Valid Seurat object saved as RDS file\n\n")
  cat("AUTHOR:\n")
  cat("  Generated by Claude (Anthropic), Curated by Ryan Routsong (NIH)\n\n")
}

# Check for help flag or validate arguments
if (length(args) == 1 && (args[1] == "-h" || args[1] == "--help")) {
  show_help()
  quit(status = 0)
}

if (length(args) != 1) {
  cat("Error: Exactly one argument required.\n\n")
  show_help()
  quit(status = 1)
}

rds_path <- args[1]

# Check if file exists
if (!file.exists(rds_path)) {
  cat("Error: File", rds_path, "does not exist.\n")
  quit(status = 1)
}

# Read the Seurat object
cat("Reading Seurat object from:", rds_path, "\n")
cat(rep("=", 60), "\n", sep = "")

tryCatch({
  seurat_obj <- readRDS(rds_path)
}, error = function(e) {
  cat("Error reading RDS file:", e$message, "\n")
  quit(status = 1)
})

# Check if it's a Seurat object
if (!inherits(seurat_obj, "Seurat")) {
  cat("Error: The RDS file does not contain a Seurat object.\n")
  quit(status = 1)
}

cat("\n")

# Basic object information
cat("SEURAT OBJECT SUMMARY\n")
cat(rep("=", 60), "\n", sep = "")
cat("Class:", class(seurat_obj)[1], "\n")
cat("Number of cells:", ncol(seurat_obj), "\n")
cat("Number of features:", nrow(seurat_obj), "\n")
cat("\n")

# Assays information
cat("ASSAYS\n")
cat(rep("-", 30), "\n", sep = "")
assays <- names(seurat_obj@assays)
for (i in 1:length(assays)) {
  assay_name <- assays[i]
  assay <- seurat_obj@assays[[assay_name]]
  cat(sprintf("%d. %s\n", i, assay_name))
  cat(sprintf("   Features: %d\n", nrow(assay)))
  cat(sprintf("   Cells: %d\n", ncol(assay)))
  
  # Show available slots for each assay (compatible with Seurat v4 and v5)
  slots_available <- c()
  
  # Check for counts data
  if (inherits(assay, "Assay5")) {
    # Seurat v5 structure
    if (length(assay@layers) > 0) {
      layer_names <- names(assay@layers)
      if ("counts" %in% layer_names && length(assay@layers$counts) > 0) {
        slots_available <- c(slots_available, "counts")
      }
      if ("data" %in% layer_names && length(assay@layers$data) > 0) {
        slots_available <- c(slots_available, "data")
      }
      if ("scale.data" %in% layer_names && length(assay@layers$scale.data) > 0) {
        slots_available <- c(slots_available, "scale.data")
      }
    }
  } else {
    # Seurat v4 structure
    tryCatch({
      if (length(assay@counts) > 0) slots_available <- c(slots_available, "counts")
    }, error = function(e) {})
    
    tryCatch({
      if (length(assay@data) > 0) slots_available <- c(slots_available, "data")
    }, error = function(e) {})
    
    tryCatch({
      if (length(assay@scale.data) > 0) slots_available <- c(slots_available, "scale.data")
    }, error = function(e) {})
  }
  
  if (length(slots_available) > 0) {
    cat(sprintf("   Available data: %s\n", paste(slots_available, collapse = ", ")))
  }
  cat("\n")
}

# Default assay
cat("Default assay:", DefaultAssay(seurat_obj), "\n\n")

# Dimensionality reductions
cat("DIMENSIONALITY REDUCTIONS\n")
cat(rep("-", 30), "\n", sep = "")
reductions <- names(seurat_obj@reductions)
if (length(reductions) > 0) {
  for (reduction in reductions) {
    red_obj <- seurat_obj@reductions[[reduction]]
    
    # Get the assay used for this reduction
    assay_used <- tryCatch({
      # Try to get assay from the reduction object
      if (!is.null(red_obj@assay.used) && red_obj@assay.used != "") {
        red_obj@assay.used
      } else {
        "Not specified"
      }
    }, error = function(e) {
      "Not specified"
    })
    
    cat(sprintf("• %s: %d dimensions (assay: %s)\n", 
                reduction, 
                ncol(red_obj@cell.embeddings),
                assay_used))
  }
} else {
  cat("No dimensionality reductions found.\n")
}

# Metadata columns
cat("METADATA COLUMNS\n")
cat(rep("-", 30), "\n", sep = "")
metadata <- seurat_obj@meta.data
cat("Number of metadata columns:", ncol(metadata), "\n")
cat("Metadata column names:\n")

for (i in 1:ncol(metadata)) {
  col_name <- colnames(metadata)[i]
  col_class <- class(metadata[[col_name]])[1]
  
  # Get summary info based on column type
  if (is.numeric(metadata[[col_name]])) {
    summary_info <- sprintf("(numeric: %.2f - %.2f)", 
                           min(metadata[[col_name]], na.rm = TRUE),
                           max(metadata[[col_name]], na.rm = TRUE))
  } else if (is.factor(metadata[[col_name]]) || is.character(metadata[[col_name]])) {
    n_unique <- length(unique(metadata[[col_name]]))
    summary_info <- sprintf("(%s: %d unique values)", col_class, n_unique)
  } else {
    summary_info <- sprintf("(%s)", col_class)
  }
  
  cat(sprintf("%2d. %-20s %s\n", i, col_name, summary_info))
}
cat("\n")

# Cluster information (if available)
if ("seurat_clusters" %in% colnames(metadata)) {
  cat("CLUSTERING INFORMATION\n")
  cat(rep("-", 30), "\n", sep = "")
  clusters <- table(metadata$seurat_clusters)
  cat("Number of clusters:", length(clusters), "\n")
  cat("Cells per cluster:\n")
  for (cluster in names(clusters)) {
    cat(sprintf("  Cluster %s: %d cells\n", cluster, clusters[cluster]))
  }
  cat("\n")
}
cat("\n")

# Active identity
cat("ACTIVE IDENTITY\n")
cat(rep("-", 30), "\n", sep = "")
cat("Active identity class:", class(Idents(seurat_obj))[1], "\n")
if (is.factor(Idents(seurat_obj))) {
  cat("Identity levels:", length(levels(Idents(seurat_obj))), "\n")
  if (length(levels(Idents(seurat_obj))) <= 20) {
    cat("Levels:", paste(levels(Idents(seurat_obj)), collapse = ", "), "\n")
  }
}
cat("\n")

# Additional useful slots
cat("ADDITIONAL INFORMATION\n")
cat(rep("-", 30), "\n", sep = "")

# Commands
if (length(seurat_obj@commands) > 0) {
  cat("Commands run:", length(seurat_obj@commands), "\n")
  recent_commands <- tail(names(seurat_obj@commands), 5)
  cat("Recent commands:", paste(recent_commands, collapse = ", "), "\n")
}

# Graphs
if (length(seurat_obj@graphs) > 0) {
  cat("Graphs:", paste(names(seurat_obj@graphs), collapse = ", "), "\n")
}

# Neighbors
if (length(seurat_obj@neighbors) > 0) {
  cat("Neighbors:", paste(names(seurat_obj@neighbors), collapse = ", "), "\n")
}

# Spatial information (if available)
if (length(seurat_obj@images) > 0) {
  cat("SPATIAL INFORMATION\n")
  cat(rep("=", 60), "\n", sep = "")
  
  # Get image/slide names
  image_names <- names(seurat_obj@images)
  cat(sprintf("Number of spatial slides/images: %d\n", length(image_names)))
  cat("\n")
  
  # Iterate through each spatial image/slide
  for (i in 1:length(image_names)) {
    img_name <- image_names[i]
    img_obj <- seurat_obj@images[[img_name]]
    
    cat(sprintf("SLIDE %d: %s\n", i, img_name))
    cat(rep("-", 50), "\n", sep = "")
    
    # Get cells associated with this image
    cells_in_image <- Cells(img_obj)
    cat(sprintf("  Number of spots/cells: %d\n", length(cells_in_image)))
    
    # Get image class and key
    cat(sprintf("  Image class: %s\n", class(img_obj)[1]))
    if (!is.null(img_obj@key)) {
      cat(sprintf("  Image key: %s\n", img_obj@key))
    }
    
    # Get assay information for this image
    if (!is.null(img_obj@assay)) {
      cat(sprintf("  Associated assay: %s\n", img_obj@assay))
    }
    
    # Get coordinate information
    coords <- NULL
    
    # Handle different Visium versions
    if (inherits(img_obj, "VisiumV2")) {
      # VisiumV2 uses @boundaries slot
      if (!is.null(img_obj@boundaries) && length(img_obj@boundaries) > 0) {
        # Get the first boundary (typically "centroids")
        if ("centroids" %in% names(img_obj@boundaries)) {
          coords <- img_obj@boundaries$centroids
        } else {
          coords <- img_obj@boundaries[[1]]
        }
      }
    } else if (inherits(img_obj, "VisiumV1")) {
      # VisiumV1 uses @coordinates slot
      if (!is.null(img_obj@coordinates)) {
        coords <- img_obj@coordinates
      }
    } else {
      # Try generic slot access for other types
      tryCatch({
        if (!is.null(img_obj@coordinates)) {
          coords <- img_obj@coordinates
        }
      }, error = function(e) {})
    }
    
    if (!is.null(coords)) {
      # Convert to data frame if it's an S4 object
      if (isS4(coords)) {
        coords <- tryCatch({
          as.data.frame(coords)
        }, error = function(e) {
          # If conversion fails, try to extract slots manually
          NULL
        })
      }
      
      if (!is.null(coords) && (is.data.frame(coords) || is.matrix(coords))) {
        cat(sprintf("  Coordinate columns: %s\n", paste(colnames(coords), collapse = ", ")))
        
        # Show coordinate ranges if numeric columns exist
        numeric_coords <- sapply(coords, is.numeric)
        if (any(numeric_coords)) {
          cat("  Coordinate ranges:\n")
          for (coord_col in names(coords)[numeric_coords]) {
            coord_range <- range(coords[[coord_col]], na.rm = TRUE)
            cat(sprintf("    %s: %.2f to %.2f\n", coord_col, coord_range[1], coord_range[2]))
          }
        }
        
        # Check for tissue positions (common in Visium data)
        if ("tissue" %in% colnames(coords)) {
          tissue_counts <- table(coords$tissue)
          cat(sprintf("  Spots in tissue: %d\n", sum(coords$tissue == 1, na.rm = TRUE)))
          cat(sprintf("  Spots outside tissue: %d\n", sum(coords$tissue == 0, na.rm = TRUE)))
        }
      }
    }
    
    # Get scaling factors if available
    if (inherits(img_obj, "VisiumV1") || inherits(img_obj, "VisiumV2")) {
      # Check for scale.factors slot (may not exist in all versions)
      has_scale_factors <- tryCatch({
        !is.null(img_obj@scale.factors)
      }, error = function(e) FALSE)
      
      if (has_scale_factors) {
        cat("  Scale factors:\n")
        scale_factors <- img_obj@scale.factors
        for (sf_name in names(scale_factors)) {
          cat(sprintf("    %s: %.4f\n", sf_name, scale_factors[[sf_name]]))
        }
      }
      
      # Get spot radius if available (typically only in VisiumV1)
      has_spot_radius <- tryCatch({
        !is.null(img_obj@spot.radius)
      }, error = function(e) FALSE)
      
      if (has_spot_radius) {
        cat(sprintf("  Spot radius: %.4f\n", img_obj@spot.radius))
      }
    }
    
    # Get image dimensions if available
    if (inherits(img_obj, "VisiumV1") || inherits(img_obj, "VisiumV2")) {
      # Check for image slot (may not exist in all versions)
      has_image <- tryCatch({
        !is.null(img_obj@image)
      }, error = function(e) FALSE)
      
      if (has_image) {
        img_dims <- dim(img_obj@image)
        if (!is.null(img_dims) && length(img_dims) >= 2) {
          cat(sprintf("  Image dimensions: %d x %d pixels\n", img_dims[1], img_dims[2]))
          if (length(img_dims) == 3) {
            cat(sprintf("  Color channels: %d\n", img_dims[3]))
          }
        }
      }
    }
    
    # Calculate and display spatial metrics if coordinates are available
    # Get coords using same logic as above
    coords_for_metrics <- NULL
    
    if (inherits(img_obj, "VisiumV2")) {
      if (!is.null(img_obj@boundaries) && length(img_obj@boundaries) > 0) {
        if ("centroids" %in% names(img_obj@boundaries)) {
          coords_for_metrics <- img_obj@boundaries$centroids
        } else {
          coords_for_metrics <- img_obj@boundaries[[1]]
        }
      }
    } else if (inherits(img_obj, "VisiumV1")) {
      if (!is.null(img_obj@coordinates)) {
        coords_for_metrics <- img_obj@coordinates
      }
    } else {
      tryCatch({
        if (!is.null(img_obj@coordinates)) {
          coords_for_metrics <- img_obj@coordinates
        }
      }, error = function(e) {})
    }
    
    if (!is.null(coords_for_metrics)) {
      # Convert to data frame if it's an S4 object
      if (isS4(coords_for_metrics)) {
        coords_for_metrics <- tryCatch({
          as.data.frame(coords_for_metrics)
        }, error = function(e) {
          NULL
        })
      }
      
      if (!is.null(coords_for_metrics) && (is.data.frame(coords_for_metrics) || is.matrix(coords_for_metrics))) {
        # Check for common coordinate column names
        x_col <- NULL
        y_col <- NULL
        if ("imagerow" %in% colnames(coords_for_metrics) && "imagecol" %in% colnames(coords_for_metrics)) {
          x_col <- "imagecol"
          y_col <- "imagerow"
        } else if ("row" %in% colnames(coords_for_metrics) && "col" %in% colnames(coords_for_metrics)) {
          x_col <- "col"
          y_col <- "row"
        } else if ("x" %in% colnames(coords_for_metrics) && "y" %in% colnames(coords_for_metrics)) {
          x_col <- "x"
          y_col <- "y"
        }
        
        if (!is.null(x_col) && !is.null(y_col)) {
          # Calculate spatial extent
          x_range <- range(coords_for_metrics[[x_col]], na.rm = TRUE)
          y_range <- range(coords_for_metrics[[y_col]], na.rm = TRUE)
          cat(sprintf("  Spatial extent (X): %.2f to %.2f\n", x_range[1], x_range[2]))
          cat(sprintf("  Spatial extent (Y): %.2f to %.2f\n", y_range[1], y_range[2]))
          
          # Calculate spot density (spots per unit area)
          area <- (x_range[2] - x_range[1]) * (y_range[2] - y_range[1])
          if (area > 0) {
            density <- length(cells_in_image) / area
            cat(sprintf("  Spot density: %.4f spots per square unit\n", density))
          }
        }
      }
    }
    
    # Check for metadata columns specific to this image
    if (img_name %in% colnames(metadata)) {
      cat(sprintf("  Metadata column '%s' present\n", img_name))
    }
    
    cat("\n")
  }
  
  # Summary statistics across all slides
  if (length(image_names) > 1) {
    cat("SPATIAL SUMMARY (All Slides)\n")
    cat(rep("-", 50), "\n", sep = "")
    
    total_spatial_cells <- sum(sapply(seurat_obj@images, function(x) length(Cells(x))))
    cat(sprintf("Total spots/cells across all slides: %d\n", total_spatial_cells))
    
    # Check if cells belong to multiple images (unusual but possible)
    if (total_spatial_cells != ncol(seurat_obj)) {
      cat(sprintf("Note: Object has %d total cells, spatial images account for %d\n", 
                  ncol(seurat_obj), total_spatial_cells))
    }
    cat("\n")
  }
  
  # Check for spatial-related metadata columns
  spatial_meta_cols <- c()
  common_spatial_cols <- c("orig.ident", "slice", "region", "sample", "array", 
                          "slide", "capture_area", "section")
  for (col in common_spatial_cols) {
    if (col %in% colnames(metadata)) {
      spatial_meta_cols <- c(spatial_meta_cols, col)
    }
  }
  
  if (length(spatial_meta_cols) > 0) {
    cat("SPATIAL-RELATED METADATA\n")
    cat(rep("-", 50), "\n", sep = "")
    cat("Detected spatial metadata columns:\n")
    for (col in spatial_meta_cols) {
      n_unique <- length(unique(metadata[[col]]))
      cat(sprintf("  • %s: %d unique values\n", col, n_unique))
      if (n_unique <= 10) {
        cat(sprintf("    Values: %s\n", paste(unique(metadata[[col]]), collapse = ", ")))
      }
    }
    cat("\n")
  }
  
  # Check for FOV (Field of View) objects (for newer spatial technologies)
  if (length(seurat_obj@images) > 0) {
    fov_count <- sum(sapply(seurat_obj@images, function(x) inherits(x, "FOV")))
    if (fov_count > 0) {
      cat("FIELD OF VIEW (FOV) INFORMATION\n")
      cat(rep("-", 50), "\n", sep = "")
      cat(sprintf("Number of FOVs: %d\n", fov_count))
      
      fov_names <- names(seurat_obj@images)[sapply(seurat_obj@images, function(x) inherits(x, "FOV"))]
      for (fov_name in fov_names) {
        fov_obj <- seurat_obj@images[[fov_name]]
        cat(sprintf("  FOV: %s\n", fov_name))
        if (!is.null(fov_obj@boundaries)) {
          cat(sprintf("    Boundaries: %s\n", paste(names(fov_obj@boundaries), collapse = ", ")))
        }
        if (!is.null(fov_obj@molecules)) {
          cat(sprintf("    Molecules: %d features\n", length(fov_obj@molecules)))
        }
      }
      cat("\n")
    }
  }
}

cat("\n")
cat(rep("=", 60), "\n", sep = "")
cat("Summary complete!\n")